# Auto generated by ct-mksetup
# Do not edit this file, edit ./project.py instead

from setuptools import setup
setup(
    **{   'author': 'Tim Diels',
    'author_email': 'timdiels.m@gmail.com',
    'classifiers': [   'Natural Language :: English',
                       'Intended Audience :: Developers',
                       'Development Status :: 3 - Alpha',
                       'Topic :: Software Development',
                       'Operating System :: POSIX',
                       'Operating System :: POSIX :: AIX',
                       'Operating System :: POSIX :: BSD',
                       'Operating System :: POSIX :: BSD :: BSD/OS',
                       'Operating System :: POSIX :: BSD :: FreeBSD',
                       'Operating System :: POSIX :: BSD :: NetBSD',
                       'Operating System :: POSIX :: BSD :: OpenBSD',
                       'Operating System :: POSIX :: GNU Hurd',
                       'Operating System :: POSIX :: HP-UX',
                       'Operating System :: POSIX :: IRIX',
                       'Operating System :: POSIX :: Linux',
                       'Operating System :: POSIX :: Other',
                       'Operating System :: POSIX :: SCO',
                       'Operating System :: POSIX :: SunOS/Solaris',
                       'Operating System :: Unix',
                       'License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)',
                       'Programming Language :: Python',
                       'Programming Language :: Python :: 3',
                       'Programming Language :: Python :: 3 :: Only',
                       'Programming Language :: Python :: 3.2',
                       'Programming Language :: Python :: 3.3',
                       'Programming Language :: Python :: 3.4',
                       'Programming Language :: Python :: 3.5',
                       'Programming Language :: Python :: Implementation',
                       'Programming Language :: Python :: Implementation :: CPython',
                       'Programming Language :: Python :: Implementation :: Stackless'],
    'description': 'Python 3 project development tools',
    'download_url': 'https://github.com/timdiels/chicken_turtle_project/releases/v2.1.2.tar.gz',
    'entry_points': {   'console_scripts': [   'ct-mkproject = chicken_turtle_project.mkproject:main',
                                               'ct-mkvenv = chicken_turtle_project.mkvenv:main',
                                               'ct-release = chicken_turtle_project.release:main',
                                               'ct-mkdoc = chicken_turtle_project.mkdoc:main',
                                               'ct-pre-commit-hook = chicken_turtle_project.pre_commit_hook:main']},
    'extras_require': {   'dev': ['sphinx-rtd-theme', 'sphinx', 'numpydoc'],
                          'test': [   'pytest-xdist',
                                      'coverage-pth',
                                      'pytest',
                                      'pytest-env',
                                      'pytest-cov',
                                      'pytest-mock']},
    'install_requires': [   'chicken-turtle-util==1.0.0',
                            'collections-extended',
                            'more-itertools',
                            'click',
                            'plumbum',
                            'pypandoc',
                            'gitpython',
                            'pip-tools',
                            'checksumdir',
                            'versio',
                            'networkx'],
    'keywords': 'development release setuptools tools',
    'license': 'LGPL3',
    'long_description': 'Python 3 project development tools. Looks like a turtle, tastes like\n'
                        'chicken.\n'
                        '\n'
                        'Chicken Turtle Project (CTP) provides CLI tools for developing Python 3\n'
                        'projects. It makes it easier to make quality commits and releases,\n'
                        'through automating what can be automated and by verifying manual work\n'
                        'against quality requirements.\n'
                        '\n'
                        'Chicken Turtle Project is alpha. The interface may change in the future,\n'
                        'but has gained some stability (far less changes than pre v2.1.0).\n'
                        '\n'
                        'Links\n'
                        '=====\n'
                        '\n'
                        '-  `Documentation <http://pythonhosted.org/chicken_turtle_project/>`__\n'
                        '-  `PyPI <https://pypi.python.org/pypi/chicken_turtle_project/>`__\n'
                        '-  `GitHub <https://github.com/timdiels/chicken_turtle_project/>`__\n'
                        '\n'
                        'Changelist\n'
                        '==========\n'
                        '\n'
                        'v2.1.2\n'
                        '------\n'
                        '\n'
                        '-  Changed: expect tests in ``your_pkg.tests`` instead of\n'
                        '   ``your_pkg.test``\n'
                        '-  Added:\n'
                        '\n'
                        '   -  \\`project.py:package\\_name\\`: allows package name and PyPI/index\n'
                        '      name to be different\n'
                        '   -  \\`project.py:pre\\_commit\\_no\\_ignore\\`: files not to ignore in\n'
                        '      precommit checks, despite them not being tracked by git.\n'
                        '\n'
                        'v2.0.4\n'
                        '------\n'
                        '\n'
                        'No changelist\n',
    'name': 'chicken_turtle_project',
    'package_data': {'chicken_turtle_project': ['data/Makefile', 'data/conf.py', 'data/index.rst']},
    'packages': ['chicken_turtle_project', 'chicken_turtle_project.tests'],
    'url': 'https://github.com/timdiels/chicken_turtle_project',
    'version': '2.1.2'}
)
